language: node_js
node_js: 6.11.3
deploy:
  provider: heroku
  api_key:
    secure: PDAsy+kMciCfr5OOCjIs1lcTjqr4NcOv9L6znidUWSUWzQM3ewAp6qtDhApsEgAqFguTDpeDfi6kSigoVKFsVnzdgI0zLV4y13dA8YjswjRX9+CWFoRMasw/MU8ZG4JwPI3WrlrW+DjzXYpQLjnZ1LKBcMZVT6Pkbi1FcPyLMPnB+CUMQSopOz2kCCQ1VcBacS05VYOMUS4YJFOd6zrHKiY6O5WRw02DjT5E6XWIc03U60JX6GZ/wEI97vLdkQqJHpxasVGOhLU6d2h5a8Y8+VNc+SDvOZ8FCPSlge35F4qVMaLvjvs1sVL96OX5GUsyretRguE1M961Q9O+rbLm4GV/k2LAEMrQdhevPHjM7fghC4hGHMt2UIw8BImq+RmWTBiPrOJjtuCiCBMtjf5hpy4+FoNAKTNp3bNrQaOWiucHT7OM4lmqIZNGKg+ztbVa03Z6uhmajoR9bsWBAAyWN41Ug4Ar5kD4BbLORvsRISIoS8l4smRdxaRVg7W6AdlbGBdblZ08UuDsj3u0dFNTg7PDxBjbgBxqOH8jk33tUgmtwEmY5siW3RGjtS3xepgW5ESMcjIXzXAiA02Ah2gI9ttJhUoApfMfEZEoGcy6BRt8en4APrFV0LZ7SGIQHDWoPZZpQWteFJmT1TqtGTydYg+mLv37GmEMARuIeXpqO1M=
  app: beanieio
